# example for PredCls
# SGCls set MODEL.ROI_RELATION_HEAD.USE_GT_BOX True, and MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False
# SGDet set MODEL.ROI_RELATION_HEAD.USE_GT_BOX False, and MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False

# VG
CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch --master_port 10025 --nproc_per_node=2 \
  tools/relation_train_net.py \
  --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" \
  MODEL.ROI_RELATION_HEAD.USE_GT_BOX True \
  MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True \
  MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS True \
  MODEL.ROI_RELATION_HEAD.PREDICTOR VTransEPredictorGCM \
  MODEL.TRAIN_INFER False \
  DTYPE "float32" \
  SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 2 \
  SOLVER.MAX_ITER 45000 SOLVER.BASE_LR 5e-4 \
  SOLVER.SCHEDULE.TYPE WarmupMultiStepLR \
  MODEL.ROI_RELATION_HEAD.BATCH_SIZE_PER_IMAGE 512 \
  SOLVER.STEPS "(10000, 16000)" SOLVER.VAL_PERIOD 5000 \
  SOLVER.CHECKPOINT_PERIOD 5000 GLOVE_DIR tools \
  MODEL.PRETRAINED_DETECTOR_CKPT ../pretrained_ckpt/model_final.pth \
  OUTPUT_DIR tools/output/relation_baseline \
  GLOBAL_SETTING.DATASET_CHOICE VG \
  SOLVER.PRE_VAL False \
  SOLVER.GRAD_NORM_CLIP 5.0;

# GQA
CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch --master_port 10025 --nproc_per_node=2 \
  tools/relation_train_net.py \
  --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" \
  MODEL.ROI_RELATION_HEAD.USE_GT_BOX True \
  MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True \
  MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS True \
  MODEL.ROI_RELATION_HEAD.PREDICTOR VTransEPredictorGCM \
  MODEL.TRAIN_INFER False \
  DTYPE "float32" \
  SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 2 \
  SOLVER.MAX_ITER 60000 SOLVER.BASE_LR 1e-4 \
  SOLVER.SCHEDULE.TYPE WarmupMultiStepLR \
  MODEL.ROI_RELATION_HEAD.BATCH_SIZE_PER_IMAGE 512 \
  SOLVER.STEPS "(10000, 16000)" SOLVER.VAL_PERIOD 5000 \
  SOLVER.CHECKPOINT_PERIOD 5000 GLOVE_DIR tools \
  MODEL.PRETRAINED_DETECTOR_CKPT_GQA ../pretrained_ckpt/gqa_model_final_from_vg.pth \
  OUTPUT_DIR tools/output/relation_baseline \
  GLOBAL_SETTING.DATASET_CHOICE GQA_200 \
  SOLVER.PRE_VAL False \
  SOLVER.GRAD_NORM_CLIP 5.0;

# OIV6
CUDA_VISIBLE_DEVICES=0,1 python3 -m torch.distributed.launch --master_port 10025 --nproc_per_node=2 \
  tools/relation_train_net.py \
  --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" \
  MODEL.ROI_RELATION_HEAD.USE_GT_BOX False \
  MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False \
  MODEL.ROI_RELATION_HEAD.PREDICT_USE_BIAS True \
  MODEL.ROI_RELATION_HEAD.PREDICTOR VTransEPredictorGCM \
  MODEL.TRAIN_INFER False \
  DTYPE "float32" \
  SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 2 \
  SOLVER.MAX_ITER 25000 SOLVER.BASE_LR 1e-3 \
  SOLVER.SCHEDULE.TYPE WarmupMultiStepLR \
  MODEL.ROI_RELATION_HEAD.BATCH_SIZE_PER_IMAGE 512 \
  SOLVER.STEPS "(10000, 16000)" SOLVER.VAL_PERIOD 5000 \
  SOLVER.CHECKPOINT_PERIOD 5000 GLOVE_DIR tools \
  MODEL.PRETRAINED_DETECTOR_CKPT_OIV6 ../pretrained_ckpt/oiv6_det.pth \
  OUTPUT_DIR tools/output/relation_baseline \
  GLOBAL_SETTING.DATASET_CHOICE OIV6 \
  GLOBAL_SETTING.CHOOSE_BEST_MODEL_BY_METRIC _recall \
  SOLVER.PRE_VAL False \
  SOLVER.GRAD_NORM_CLIP 5.0;
